name: Test SSH Connection

on:
  workflow_dispatch:  # untuk trigger manual dari GitHub UI

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Test SSH to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          echo "✅ SSH success!"
          hostname
          whoami
          uptime
